<script src="./src/js/bootstrap.min.js"></script>
<script>
    const data = {
        allen: [
            "Alejandro Village (Santiago)",
            "Bonifacio",
            "Cabacungan",
            "Calarayan",
            "Frederic",
            "Guin-arawayan",
            "Imelda",
            "Jubasan",
            "Kinabranan Zone I (Poblacion)",
            "Kinabranan Zone II (Poblacion)",
            "Kinaguitman",
            "Lagundi",
            "Lipata",
            "Londres",
            "Lo-oc",
            "Sabang Zone I (Poblacion)",
            "Sabang Zone II (Poblacion)",
            "Santa Rita",
            "Tasvilla",
            "Victoria",
        ],
        biri: [
            "Kauswagan",
            "MacArthur",
            "Pio Del Pilar",
            "Poblacion",
            "Progresso",
            "San Antonio",
            "San Pedro",
            "Santo Niño",
        ],
        bobon: [
            "Acerida",
            "Arellano",
            "Balat-balud",
            "Calantiao",
            "Dancalan",
            "E. Duran",
            "Gen. Lucban",
            "Jose Abad Santos",
            "Jose P. Laurel",
            "Magsaysay",
            "Quezon",
            "Salvacion",
            "San Isidro",
            "San Juan",
            "Santa Clara",
            "Santander",
            "Somoroay",
            "Trojello",
        ],
        capul: [
            "Aguin",
            "Jubang",
            "Landusan",
            "Oson",
            "Sagaosawan",
            "San Luis",
            "Sawang",
            "Barangay 1 (Pob.)",
            "Barangay 2 (Pob.)",
            "Barangay 3 (Pob.)",
            "Barangay 4 (Pob.)",
            "Barangay 5 (Pob.)",
        ],
        catarman: [
            "Acacia",
            "Aguinaldo",
            "Airport Village",
            "Bangkerohan",
            "Baybay",
            "Bocsol",
            "Cabayhan",
            "Cag-abaca",
            "Calachuchi",
            "Casoy",
            "Dalakit",
            "Doña Anecita",
            "Guinbirayan",
            "Ibabao",
            "Imelda",
            "Lao-angan",
            "Libas",
            "Libertad",
            "Ligaya",
            "Magsaysay",
            "Malvar",
            "Molave",
            "Monroe",
            "Nato",
            "Pagrogan",
            "Pallogan",
            "Polangi",
            "Quezon",
            "Rizal",
            "Roxas",
            "San Andres",
            "San Julian",
            "San Roque",
            "Santa Cruz",
            "Somoge",
            "Tarusan",
            "Vega",
            "Yanang",
        ],
        catubig: [
            "Balat-Balud",
            "Bonifacio",
            "Canuctan",
            "Can-uyan",
            "Crossing",
            "Dalakit",
            "Doña Lucia",
            "Don Julio",
            "Genaro",
            "Guibwangan",
            "Haliw",
            "Inibangan",
            "Inuntungan",
            "Liberty",
            "Mananao",
            "Manarang",
            "Mapanas",
            "Matango",
            "Naubay",
            "New Rizal",
            "Old Rizal",
            "Osmeña",
            "Quezon",
            "Roxas",
            "San Jorge",
            "San Roque",
            "San Vicente",
            "Santo Niño",
            "Sinidman Oriental",
            "Sinidman Occidental",
            "Urdaneta",
        ],
        gamay: [
            "Anito",
            "Bangon",
            "Bangonay",
            "Barangay I (Pob.)",
            "Barangay II (Pob.)",
            "Barangay III (Pob.)",
            "Baybay",
            "Bonifacio",
            "Cagamutan",
            "Central",
            "Guintarcan",
            "Irawahan",
            "Limbujan",
            "Lobe-lobe",
            "Lourdes",
            "Lungib",
            "Magsaysay",
            "Matahay",
            "Napotiocan",
            "Ongol",
            "Orion",
            "Paninirongan",
            "Peña",
            "Rizal",
            "Sangcol",
            "Somoroy",
            "Tangbo",
            "Urdaneta",
        ],
        lapinig: [
            "Angeles",
            "Bagong Sikat",
            "Bangkilingan",
            "Barangay I (Pob.)",
            "Barangay II (Pob.)",
            "Barangay III (Pob.)",
            "Barangay IV (Pob.)",
            "Barangay V (Pob.)",
            "Barangay VI (Pob.)",
            "Barangay VII (Pob.)",
            "Bagumbayan",
            "Cacao",
            "Cawayan",
            "Caybani",
            "Gibale",
            "Luna",
            "Magsaysay",
            "Onggoy",
            "San Antonio",
            "San Isidro",
            "San Roque",
            "San Vicente",
        ],
        lasNavas: [
            "Anongo",
            "Cabarasan",
            "Caputo-an",
            "Catoto-ogan",
            "Cogan",
            "Cuenco",
            "Del Rosario",
            "Duran",
            "Guba",
            "Hibubullao",
            "Hinagonoyan",
            "Imelda",
            "Javier",
            "Luisita",
            "Magsaysay",
            "Maningning",
            "Mapno",
            "Montaneza",
            "Osang",
            "P. Rebadulla",
            "Poponton",
            "Quezon",
            "Quirino",
            "Roxas",
            "San Francisco",
            "San Isidro",
            "San Jorge",
            "San Miguel",
            "San Vicente",
            "Santa Isabel",
            "Santo Tomas",
            "Sugod",
            "Tagab-iran",
            "Taylor",
            "Victory",
        ],
        lavezares: [
            "Balicuatro",
            "Barobaybay",
            "Bonifacio",
            "Caburihan",
            "Cleopatra",
            "Enriqueta",
            "Libertad",
            "Lloyd",
            "Magsaysay",
            "Maguino-o",
            "Maragat",
            "Maravilla",
            "Pilar",
            "Poblacion A (Pob.)",
            "Poblacion B (Pob.)",
            "Rizal",
            "San Agustin",
            "San Isidro",
            "San Jose",
            "San Juan",
            "San Miguel",
            "San Vicente",
            "Santo Domingo",
            "Santo Niño",
            "Villa S. Virgilia",
            "Washington",
            "Wilson",
        ],
        lopeDeVega: [
            "Bonifacio",
            "Cag-amesarag",
            "Cag-manaba",
            "Gen. Luna",
            "Gen. Malvar",
            "Gurangpa",
            "Hen. Magsaysay",
            "Lope De Vega (Pob.)",
            "Lower Caynaga",
            "Lower Puray",
            "Lukay",
            "Marupangdan",
            "Osmeña",
            "Quezon",
            "Rizal",
            "San Isidro",
            "San Miguel",
            "San Pedro",
            "San Vicente",
            "Santol",
            "Santo Tomas",
            "Uningan",
            "Upper Caynaga",
            "Upper Puray",
        ],
        mapanas: [
            "Asum",
            "Balat-balud",
            "Ban-as",
            "Bugko",
            "Cagbungal",
            "Calantiao",
            "Dancalan",
            "Duran",
            "E. J. Dulay",
            "Geadgawan",
            "Jose Abad Santos",
            "Magsaysay",
            "Maligaya",
            "Maragano",
            "Osmeña",
            "Salvacion",
            "San Isidro",
            "Santissima Trinidad",
            "Somoge",
            "Dapdap (Pob.)",
            "Mabini (Pob.)",
            "Jose P. Laurel (Pob.)",
        ],
        mondragon: [
            "Bagasbas",
            "Bugko",
            "Cablangan",
            "Cabil-isan",
            "Cag-amesarag",
            "Cag-sumangkay",
            "Calicate",
            "Calingcosan",
            "Capanag",
            "Casili-on",
            "Dancalan",
            "Flora",
            "Hinabangan",
            "Malinao",
            "Marubay",
            "Mongol",
            "Osmeña",
            "P. Rebadulla",
            "Rizal",
            "Roxas",
            "San Agustin",
            "San Antonio",
            "San Isidro",
            "San Jose",
            "San Juan",
            "San Miguel",
            "San Roque",
            "Santa Catalina",
            "Santa Teresita",
            "Santo Niño",
            "Tinaplacan",
            "Tomas Oppus",
            "Victory",
        ],
        palapag: [
            "Bagacay",
            "Bagong Lipunan",
            "Bancasan",
            "Binaloan",
            "Binay",
            "Burabod",
            "Cabariwan",
            "Calomotan",
            "Cansangaya",
            "Caputoan",
            "Camayse",
            "Can-aga",
            "Dancalan",
            "Gamay",
            "Gen. Malvar",
            "Limbuhan",
            "Mabini",
            "Magsaysay",
            "Manahao",
            "Manato Central",
            "Manato East",
            "Manato West",
            "Mansarol",
            "Mauo",
            "Osmeña",
            "Palaypay",
            "Puro",
            "Quezon",
            "Rizal",
            "San Agustin",
            "San Fernando",
            "San Jose",
            "San Juan",
            "San Miguel",
            "Santa Maria",
            "Santo Niño",
            "Sumoroy",
            "Talolora",
            "Tatabunan",
            "Tongcop",
        ],
        pambujan: [
            "Acedillo",
            "Balocawe",
            "Baybay",
            "Binay",
            "Cababto-an",
            "Cabay-an",
            "Cahicsan",
            "Cahipay",
            "Canjumadal",
            "Caticugan",
            "Daanpuro",
            "G. Escarez",
            "Ginulgan",
            "Imelda",
            "L. Empon",
            "Lo-ok",
            "Mabuhay",
            "Magtaon",
            "Manaybanay",
            "Mansarang",
            "Mansarol",
            "Nato",
            "Nato East",
            "Nato West",
            "Poblacion",
            "Quirino",
            "San Antonio",
            "San Isidro",
            "San Jose",
            "San Juan",
            "San Miguel",
            "San Roque",
            "San Vicente",
            "Santa Rita",
            "Santa Rosa",
            "Tabon-tabon",
            "Tagab-iran",
            "Taylor",
            "Victory",
        ],
        rosario: [
            "Bagong Lipunan",
            "Bonifacio",
            "Buenavista",
            "Cabay-an",
            "Cabarasan",
            "Cag-amesarag",
            "Calantiao",
            "Calingcosan",
            "Capanag",
            "Caputoan",
            "Casili-on",
            "Dapdap",
            "Gueda",
            "Guin-ansan",
            "Guintarcan",
            "Hinagonoyan",
            "Libertad",
            "Lubo",
            "Magsaysay",
            "Maningning",
            "Mapanas",
            "Matahay",
            "Palamrag",
            "Paninirongan",
            "Pintuyan",
            "Rizal",
            "Sangcol",
            "San Isidro",
            "San Jose",
            "San Miguel",
            "San Roque",
            "San Vicente",
            "Santa Maria",
            "Santa Rita",
            "Santa Rosa",
            "Santo Niño",
            "Santo Tomas",
            "Sugod",
            "Tagab-iran",
            "Taylor",
            "Tongcop",
            "Victory",
        ],
        sanAntonio: [
            "Barangay 1 (Pob.)",
            "Barangay 2 (Pob.)",
            "Barangay 3 (Pob.)",
            "Barangay 4 (Pob.)",
            "Barangay 5 (Pob.)",
            "Barangay 6 (Pob.)",
            "Barangay 7 (Pob.)",
            "Barangay 8 (Pob.)",
            "Barangay 9 (Pob.)",
            "Barangay 10 (Pob.)",
            "Barangay 11 (Pob.)",
            "Barangay 12 (Pob.)",
            "Barangay 13 (Pob.)",
            "Barangay 14 (Pob.)",
            "Barangay 15 (Pob.)",
            "Barangay 16 (Pob.)",
            "Barangay 17 (Pob.)",
            "Barangay 18 (Pob.)",
            "Barangay 19 (Pob.)",
            "Barangay 20 (Pob.)",
        ],
        sanIsidro: [
            "Balat-balud",
            "Bonifacio",
            "Cabacungan",
            "Cagbangon",
            "Cagbalogo",
            "Cahicsan",
            "Cahipay",
            "Calantiao",
            "Calingcosan",
            "Canuctan",
            "Caputoan",
            "Dancalan",
            "Duran",
            "Gueda",
            "Guintarcan",
            "Hinagonoyan",
            "Lubo",
            "Magsaysay",
            "Manarayao",
            "Mapanas",
            "Matahay",
            "Osang",
            "Pintuyan",
            "Rizal",
            "San Agustin",
            "San Isidro",
            "San Jose",
            "San Juan",
            "San Miguel",
            "San Roque",
            "San Vicente",
            "Santa Maria",
            "Santa Rita",
            "Santa Rosa",
            "Santo Niño",
            "Santo Tomas",
            "Sugod",
            "Tagab-iran",
            "Taylor",
            "Tongcop",
            "Victory",
        ],
        sanJose: [
            "Acedillo",
            "Bagacay",
            "Bagong Lipunan",
            "Binay",
            "Bonifacio",
            "Buenavista",
            "Cababto-an",
            "Cabay-an",
            "Cadingayan",
            "Cag-amesarag",
            "Cagbalogo",
            "Calantiao",
            "Calingcosan",
            "Canuctan",
            "Caputoan",
            "Casili-on",
            "Dapdap",
            "Gueda",
            "Guin-ansan",
            "Guinob-an",
            "Hinagonoyan",
            "Libertad",
            "Lubo",
            "Magsaysay",
            "Manarayao",
            "Mapanas",
            "Osang",
            "Pintuyan",
            "Rizal",
            "Sangcol",
            "San Agustin",
            "San Isidro",
            "San Jose",
            "San Juan",
            "San Miguel",
            "San Roque",
            "San Vicente",
            "Santa Maria",
            "Santa Rita",
            "Santa Rosa",
            "Santo Niño",
            "Santo Tomas",
            "Sugod",
            "Tagab-iran",
            "Taylor",
            "Tongcop",
            "Victory",
        ],
        sanRoque: [
            "Alang-alang",
            "Barangay I (Pob.)",
            "Barangay II (Pob.)",
            "Barangay III (Pob.)",
            "Barangay IV (Pob.)",
            "Barangay V (Pob.)",
            "Bongog",
            "Cagbugna",
            "Canomay",
            "Gabus",
            "Maga",
            "Magsaysay",
            "Magsaysay (Lourdes)",
            "Poblacion",
            "Rizal",
            "San Agustin",
            "San Antonio",
            "San Francisco",
            "San Isidro",
            "San Jose",
            "San Juan",
            "San Miguel",
            "San Vicente",
            "Santa Catalina",
            "Santa Rita",
            "Santa Rosa",
            "Santo Niño",
            "Santo Tomas",
            "Sugod",
            "Tagab-iran",
            "Taylor",
            "Tongcop",
            "Victory",
        ],
        sanVicente: [
            "Anoling",
            "Barangay I (Pob.)",
            "Barangay II (Pob.)",
            "Barangay III (Pob.)",
            "Barangay IV (Pob.)",
            "Barangay V (Pob.)",
            "Barangay VI (Pob.)",
            "Barangay VII (Pob.)",
            "Barangay VIII (Pob.)",
            "Barangay IX (Pob.)",
            "Barangay X (Pob.)",
            "Barangay XI (Pob.)",
            "Barangay XII (Pob.)",
            "Barangay XIII (Pob.)",
            "Barangay XIV (Pob.)",
            "Barangay XV (Pob.)",
            "Barangay XVI (Pob.)",
            "Barangay XVII (Pob.)",
            "Barangay XVIII (Pob.)",
            "Barangay XIX (Pob.)",
            "Barangay XX (Pob.)",
        ],
        silvinoLobos: [
            "Barangay I (Pob.)",
            "Barangay II (Pob.)",
            "Barangay III (Pob.)",
            "Barangay IV (Pob.)",
            "Barangay V (Pob.)",
            "Barangay VI (Pob.)",
            "Barangay VII (Pob.)",
            "Barangay VIII (Pob.)",
            "Barangay IX (Pob.)",
            "Barangay X (Pob.)",
            "Barangay XI (Pob.)",
            "Barangay XII (Pob.)",
            "Barangay XIII (Pob.)",
            "Barangay XIV (Pob.)",
            "Barangay XV (Pob.)",
            "Barangay XVI (Pob.)",
            "Barangay XVII (Pob.)",
            "Barangay XVIII (Pob.)",
            "Barangay XIX (Pob.)",
            "Barangay XX (Pob.)",
        ],
        victoria: [
            "Barangay I (Pob.)",
            "Barangay II (Pob.)",
            "Barangay III (Pob.)",
            "Barangay IV (Pob.)",
            "Barangay V (Pob.)",
            "Barangay VI (Pob.)",
            "Barangay VII (Pob.)",
            "Barangay VIII (Pob.)",
            "Barangay IX (Pob.)",
            "Barangay X (Pob.)",
            "Barangay XI (Pob.)",
            "Barangay XII (Pob.)",
            "Barangay XIII (Pob.)",
            "Barangay XIV (Pob.)",
            "Barangay XV (Pob.)",
            "Barangay XVI (Pob.)",
            "Barangay XVII (Pob.)",
            "Barangay XVIII (Pob.)",
            "Barangay XIX (Pob.)",
            "Barangay XX (Pob.)",
        ],
    };

    const municipalitySelect = document.getElementById("municipalitySelect");
    const barangaySelect = document.getElementById("barangaySelect");

    municipalitySelect.addEventListener("change", function() {
        const selectedMunicipality = this.value;
        const barangays = data[selectedMunicipality];

        barangaySelect.innerHTML =
            `<option value="" selected disabled>Choose a barangay</option>`;
        barangays.forEach((barangay) => {
            const option = document.createElement("option");
            option.value = barangay;
            option.textContent = barangay;
            barangaySelect.appendChild(option);
        });

        barangaySelect.disabled = false;
    });
</script>
</body>

</html>